import { Injectable } from '@nestjs/common';

@Injectable()
export class CurrencyDataProvider {
  getCurrencyData() {
    return [
      { code: 'BDT', name: 'Bangladeshi taka', symbol: '৳', flag: '🇧🇩' },
      {
        code: 'AED',
        name: 'United Arab Emirates dirham',
        symbol: 'د.إ',
        flag: '🇦🇪',
      },
      { code: 'AFN', name: 'Afghan afghani', symbol: '؋', flag: '🇦🇫' },
      { code: 'ALL', name: 'Albanian lek', symbol: 'L', flag: '🇦🇱' },
      { code: 'AMD', name: 'Armenian dram', symbol: '֏', flag: '🇦🇲' },
      {
        code: 'ANG',
        name: 'Netherlands Antillean guilder',
        symbol: 'ƒ',
        flag: '🇨🇼',
      },
      { code: 'AOA', name: 'Angolan kwanza', symbol: 'Kz', flag: '🇦🇴' },
      { code: 'ARS', name: 'Argentine peso', symbol: '$', flag: '🇦🇷' },
      { code: 'AUD', name: 'Australian dollar', symbol: '$', flag: '🇦🇺' },
      { code: 'AWG', name: 'Aruban florin', symbol: 'ƒ', flag: '🇦🇼' },
      { code: 'AZN', name: 'Azerbaijani manat', symbol: '₼', flag: '🇦🇿' },
      {
        code: 'BAM',
        name: 'Bosnia and Herzegovina convertible mark',
        symbol: 'КМ',
        flag: '🇧🇦',
      },
      { code: 'BBD', name: 'Barbados dollar', symbol: '$', flag: '🇧🇧' },
      { code: 'BGN', name: 'Bulgarian lev', symbol: 'лв', flag: '🇧🇬' },
      { code: 'BHD', name: 'Bahraini dinar', symbol: '.د.ب', flag: '🇧🇭' },
      { code: 'BIF', name: 'Burundian franc', symbol: 'FBu', flag: '🇧🇮' },
      { code: 'BMD', name: 'Bermudian dollar', symbol: '$', flag: '🇧🇲' },
      { code: 'BND', name: 'Brunei dollar', symbol: '$', flag: '🇧🇳' },
      { code: 'BOB', name: 'Boliviano', symbol: 'Bs.', flag: '🇧🇴' },
      { code: 'BRL', name: 'Brazilian real', symbol: 'R$', flag: '🇧🇷' },
      { code: 'BSD', name: 'Bahamian dollar', symbol: '$', flag: '🇧🇸' },
      { code: 'BTN', name: 'Bhutanese ngultrum', symbol: 'Nu.', flag: '🇧🇹' },
      { code: 'BWP', name: 'Botswana pula', symbol: 'P', flag: '🇧🇼' },
      { code: 'BYN', name: 'Belarusian ruble', symbol: 'Br', flag: '🇧🇾' },
      { code: 'BZD', name: 'Belize dollar', symbol: '$', flag: '🇧🇿' },
      { code: 'CAD', name: 'Canadian dollar', symbol: '$', flag: '🇨🇦' },
      { code: 'CDF', name: 'Congolese franc', symbol: 'FC', flag: '🇨🇩' },
      { code: 'CHF', name: 'Swiss franc', symbol: 'CHF', flag: '🇨🇭' },
      { code: 'CLP', name: 'Chilean peso', symbol: '$', flag: '🇨🇱' },
      { code: 'CNY', name: 'Renminbi (Chinese) yuan', symbol: '¥', flag: '🇨🇳' },
      { code: 'COP', name: 'Colombian peso', symbol: '$', flag: '🇨🇴' },
      { code: 'CRC', name: 'Costa Rican colon', symbol: '₡', flag: '🇨🇷' },
      { code: 'CUC', name: 'Cuban convertible peso', symbol: '$', flag: '🇨🇺' },
      { code: 'CUP', name: 'Cuban peso', symbol: '$', flag: '🇨🇺' },
      { code: 'CVE', name: 'Cape Verdean escudo', symbol: '$', flag: '🇨🇻' },
      { code: 'CZK', name: 'Czech koruna', symbol: 'Kč', flag: '🇨🇿' },
      { code: 'DJF', name: 'Djiboutian franc', symbol: 'Fdj', flag: '🇩🇯' },
      { code: 'DKK', name: 'Danish krone', symbol: 'kr', flag: '🇩🇰' },
      { code: 'DOP', name: 'Dominican peso', symbol: '$', flag: '🇩🇴' },
      { code: 'DZD', name: 'Algerian dinar', symbol: 'د.ج', flag: '🇩🇿' },
      { code: 'EGP', name: 'Egyptian pound', symbol: '£', flag: '🇪🇬' },
      { code: 'ERN', name: 'Eritrean nakfa', symbol: 'Nfk', flag: '🇪🇷' },
      { code: 'ETB', name: 'Ethiopian birr', symbol: 'Br', flag: '🇪🇹' },
      { code: 'EUR', name: 'Euro', symbol: '€', flag: '🇪🇺' },
      { code: 'FJD', name: 'Fiji dollar', symbol: '$', flag: '🇫🇯' },
      { code: 'FKP', name: 'Falkland Islands pound', symbol: '£', flag: '🇫🇰' },
      { code: 'GBP', name: 'Pound sterling', symbol: '£', flag: '🇬🇧' },
      { code: 'GEL', name: 'Georgian lari', symbol: '₾', flag: '🇬🇪' },
      { code: 'GHS', name: 'Ghanaian cedi', symbol: '₵', flag: '🇬🇭' },
      { code: 'GIP', name: 'Gibraltar pound', symbol: '£', flag: '🇬🇮' },
      { code: 'GMD', name: 'Gambian dalasi', symbol: 'D', flag: '🇬🇲' },
      { code: 'GNF', name: 'Guinean franc', symbol: 'FG', flag: '🇬🇳' },
      { code: 'GTQ', name: 'Guatemalan quetzal', symbol: 'Q', flag: '🇬🇹' },
      { code: 'GYD', name: 'Guyanese dollar', symbol: '$', flag: '🇬🇾' },
      { code: 'HKD', name: 'Hong Kong dollar', symbol: '$', flag: '🇭🇰' },
      { code: 'HNL', name: 'Honduran lempira', symbol: 'L', flag: '🇭🇳' },
      { code: 'HRK', name: 'Croatian kuna', symbol: 'kn', flag: '🇭🇷' },
      { code: 'HTG', name: 'Haitian gourde', symbol: 'G', flag: '🇭🇹' },
      { code: 'HUF', name: 'Hungarian forint', symbol: 'Ft', flag: '🇭🇺' },
      { code: 'IDR', name: 'Indonesian rupiah', symbol: 'Rp', flag: '🇮🇩' },
      { code: 'ILS', name: 'Israeli new shekel', symbol: '₪', flag: '🇮🇱' },
      { code: 'INR', name: 'Indian rupee', symbol: '₹', flag: '🇮🇳' },
      { code: 'IQD', name: 'Iraqi dinar', symbol: 'ع.د', flag: '🇮🇶' },
      { code: 'IRR', name: 'Iranian rial', symbol: '﷼', flag: '🇮🇷' },
      { code: 'ISK', name: 'Icelandic króna', symbol: 'kr', flag: '🇮🇸' },
      { code: 'JMD', name: 'Jamaican dollar', symbol: '$', flag: '🇯🇲' },
      { code: 'JOD', name: 'Jordanian dinar', symbol: 'د.ا', flag: '🇯🇴' },
      { code: 'JPY', name: 'Japanese yen', symbol: '¥', flag: '🇯🇵' },
      { code: 'KES', name: 'Kenyan shilling', symbol: 'Sh', flag: '🇰🇪' },
      { code: 'KGS', name: 'Kyrgyzstani som', symbol: 'с', flag: '🇰🇬' },
      { code: 'KHR', name: 'Cambodian riel', symbol: '៛', flag: '🇰🇭' },
      { code: 'KMF', name: 'Comoro franc', symbol: 'CF', flag: '🇰🇲' },
      { code: 'KPW', name: 'North Korean won', symbol: '₩', flag: '🇰🇵' },
      { code: 'KRW', name: 'South Korean won', symbol: '₩', flag: '🇰🇷' },
      { code: 'KWD', name: 'Kuwaiti dinar', symbol: 'د.ك', flag: '🇰🇼' },
      { code: 'KYD', name: 'Cayman Islands dollar', symbol: '$', flag: '🇰🇾' },
      { code: 'KZT', name: 'Kazakhstani tenge', symbol: '₸', flag: '🇰🇿' },
      { code: 'LAK', name: 'Lao kip', symbol: '₭', flag: '🇱🇦' },
      { code: 'LBP', name: 'Lebanese pound', symbol: 'ل.ل', flag: '🇱🇧' },
      { code: 'LKR', name: 'Sri Lankan rupee', symbol: 'Rs', flag: '🇱🇰' },
      { code: 'LRD', name: 'Liberian dollar', symbol: '$', flag: '🇱🇷' },
      { code: 'LSL', name: 'Lesotho loti', symbol: 'L', flag: '🇱🇸' },
      { code: 'LYD', name: 'Libyan dinar', symbol: 'ل.د', flag: '🇱🇾' },
      { code: 'MAD', name: 'Moroccan dirham', symbol: 'د.م.', flag: '🇲🇦' },
      { code: 'MDL', name: 'Moldovan leu', symbol: 'L', flag: '🇲🇩' },
      { code: 'MGA', name: 'Malagasy ariary', symbol: 'Ar', flag: '🇲🇬' },
      { code: 'MKD', name: 'Macedonian denar', symbol: 'ден', flag: '🇲🇰' },
      { code: 'MMK', name: 'Myanmar kyat', symbol: 'Ks', flag: '🇲🇲' },
      { code: 'MNT', name: 'Mongolian tögrög', symbol: '₮', flag: '🇲🇳' },
      { code: 'MOP', name: 'Macanese pataca', symbol: 'P', flag: '🇲🇴' },
      { code: 'MRU', name: 'Mauritanian ouguiya', symbol: 'UM', flag: '🇲🇷' },
      { code: 'MUR', name: 'Mauritian rupee', symbol: '₨', flag: '🇲🇺' },
      { code: 'MVR', name: 'Maldivian rufiyaa', symbol: '.ރ', flag: '🇲🇻' },
      { code: 'MWK', name: 'Malawian kwacha', symbol: 'MK', flag: '🇲🇼' },
      { code: 'MXN', name: 'Mexican peso', symbol: '$', flag: '🇲🇽' },
      { code: 'MYR', name: 'Malaysian ringgit', symbol: 'RM', flag: '🇲🇾' },
      { code: 'MZN', name: 'Mozambican metical', symbol: 'MT', flag: '🇲🇿' },
      { code: 'NAD', name: 'Namibian dollar', symbol: '$', flag: '🇳🇦' },
      { code: 'NGN', name: 'Nigerian naira', symbol: '₦', flag: '🇳🇬' },
      { code: 'NIO', name: 'Nicaraguan córdoba', symbol: 'C$', flag: '🇳🇮' },
      { code: 'NOK', name: 'Norwegian krone', symbol: 'kr', flag: '🇳🇴' },
      { code: 'NPR', name: 'Nepalese rupee', symbol: '₨', flag: '🇳🇵' },
      { code: 'NZD', name: 'New Zealand dollar', symbol: '$', flag: '🇳🇿' },
      { code: 'OMR', name: 'Omani rial', symbol: 'ر.ع.', flag: '🇴🇲' },
      { code: 'PAB', name: 'Panamanian balboa', symbol: 'B/.', flag: '🇵🇦' },
      { code: 'PEN', name: 'Peruvian sol', symbol: 'S/.', flag: '🇵🇪' },
      { code: 'PGK', name: 'Papua New Guinean kina', symbol: 'K', flag: '🇵🇬' },
      { code: 'PHP', name: 'Philippine peso', symbol: '₱', flag: '🇵🇭' },
      { code: 'PKR', name: 'Pakistani rupee', symbol: '₨', flag: '🇵🇰' },
      { code: 'PLN', name: 'Polish zloty', symbol: 'zł', flag: '🇵🇱' },
      { code: 'PYG', name: 'Paraguayan guaraní', symbol: '₲', flag: '🇵🇾' },
      { code: 'QAR', name: 'Qatari riyal', symbol: 'ر.ق', flag: '🇶🇦' },
      { code: 'RON', name: 'Romanian leu', symbol: 'lei', flag: '🇷🇴' },
      { code: 'RSD', name: 'Serbian dinar', symbol: 'дин.', flag: '🇷🇸' },
      { code: 'RUB', name: 'Russian ruble', symbol: '₽', flag: '🇷🇺' },
      { code: 'RWF', name: 'Rwandan franc', symbol: 'FRw', flag: '🇷🇼' },
      { code: 'SAR', name: 'Saudi riyal', symbol: 'ر.س', flag: '🇸🇦' },
      { code: 'SBD', name: 'Solomon Islands dollar', symbol: '$', flag: '🇸🇧' },
      { code: 'SCR', name: 'Seychelles rupee', symbol: '₨', flag: '🇸🇨' },
      { code: 'SDG', name: 'Sudanese pound', symbol: 'ج.س.', flag: '🇸🇩' },
      { code: 'SEK', name: 'Swedish krona/kronor', symbol: 'kr', flag: '🇸🇪' },
      { code: 'SGD', name: 'Singapore dollar', symbol: '$', flag: '🇸🇬' },
      { code: 'SHP', name: 'Saint Helena pound', symbol: '£', flag: '🇸🇭' },
      { code: 'SLL', name: 'Sierra Leonean leone', symbol: 'Le', flag: '🇸🇱' },
      { code: 'SOS', name: 'Somali shilling', symbol: 'Sh', flag: '🇸🇴' },
      { code: 'SRD', name: 'Surinamese dollar', symbol: '$', flag: '🇸🇷' },
      { code: 'SSP', name: 'South Sudanese pound', symbol: '£', flag: '🇸🇸' },
      {
        code: 'STN',
        name: 'São Tomé and Príncipe dobra',
        symbol: 'Db',
        flag: '🇸🇹',
      },
      { code: 'SVC', name: 'Salvadoran colón', symbol: '₡', flag: '🇸🇻' },
      { code: 'SYP', name: 'Syrian pound', symbol: '£', flag: '🇸🇾' },
      { code: 'SZL', name: 'Swazi lilangeni', symbol: 'L', flag: '🇸🇿' },
      { code: 'THB', name: 'Thai baht', symbol: '฿', flag: '🇹🇭' },
      { code: 'TJS', name: 'Tajikistani somoni', symbol: 'ЅМ', flag: '🇹🇯' },
      { code: 'TMT', name: 'Turkmenistan manat', symbol: 'm', flag: '🇹🇲' },
      { code: 'TND', name: 'Tunisian dinar', symbol: 'د.ت', flag: '🇹🇳' },
      { code: 'TOP', name: 'Tongan paʻanga', symbol: 'T$', flag: '🇹🇴' },
      { code: 'TRY', name: 'Turkish lira', symbol: '₺', flag: '🇹🇷' },
      {
        code: 'TTD',
        name: 'Trinidad and Tobago dollar',
        symbol: '$',
        flag: '🇹🇹',
      },
      { code: 'TWD', name: 'New Taiwan dollar', symbol: '$', flag: '🇹🇼' },
      { code: 'TZS', name: 'Tanzanian shilling', symbol: 'Sh', flag: '🇹🇿' },
      { code: 'UAH', name: 'Ukrainian hryvnia', symbol: '₴', flag: '🇺🇦' },
      { code: 'UGX', name: 'Ugandan shilling', symbol: 'Sh', flag: '🇺🇬' },
      { code: 'USD', name: 'United States dollar', symbol: '$', flag: '🇺🇸' },
      { code: 'UYU', name: 'Uruguayan peso', symbol: '$', flag: '🇺🇾' },
      { code: 'UZS', name: 'Uzbekistan som', symbol: "so'm", flag: '🇺🇿' },
      {
        code: 'VES',
        name: 'Venezuelan bolívar soberano',
        symbol: 'Bs.S',
        flag: '🇻🇪',
      },
      { code: 'VND', name: 'Vietnamese đồng', symbol: '₫', flag: '🇻🇳' },
      { code: 'VUV', name: 'Vanuatu vatu', symbol: 'Vt', flag: '🇻🇺' },
      { code: 'WST', name: 'Samoan tala', symbol: 'T', flag: '🇼🇸' },
      { code: 'XAF', name: 'CFA franc BEAC', symbol: 'FCFA', flag: '🇨🇲' },
      { code: 'XOF', name: 'CFA franc BCEAO', symbol: 'CFA', flag: '🇸🇳' },
      {
        code: 'XPF',
        name: 'CFP franc (franc Pacifique)',
        symbol: '₣',
        flag: '🇵🇫',
      },
      { code: 'YER', name: 'Yemeni rial', symbol: '﷼', flag: '🇾🇪' },
      { code: 'ZAR', name: 'South African rand', symbol: 'R', flag: '🇿🇦' },
      { code: 'ZMW', name: 'Zambian kwacha', symbol: 'ZK', flag: '🇿🇲' },
      { code: 'ZWL', name: 'Zimbabwean dollar', symbol: '$', flag: '🇿🇼' },
    ];
  }
}
